name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17, 19 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: build
        run: ./gradlew build publish --stacktrace --warning-mode fail
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}
      - name: capture build artifacts
        # Only upload artifacts built from latest java on one OS
        if: ${{ matrix.java == '17' && matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: enigma-swing/build/libs/
